### ISSUE TITLE
Data differences between my local version and version on site

### ISSUE THREAD

**Issue by roybgardner** [HalcyonWjr/implementation-narratives#1]
Need to check data integrity. For example, on site there are nine Ukraine agreements listed for the topic `Provisions for a ceasefire`. On my machine I see six agreements (see attached screenshot).

The `countries.js` file on my machine is the same as that in the data repo https://github.com/peacerep/implementation_narratives_data

I've also attached `countries.js` for reference as well as my demonstrator software for navigating the data tree.

<img width="986" alt="provisions_for_a_ceasefire" src="https://user-images.githubusercontent.com/11853656/226383502-c41d3c92-4914-4934-a248-81695ca444db.png">
[countries.js.zip](https://github.com/HalcyonWjr/implementation-narratives/files/11019760/countries.js.zip)
[implementation_narratives.zip](https://github.com/HalcyonWjr/implementation-narratives/files/11019775/implementation_narratives.zip)

**Comment by HalcyonWjr** [comment]
Thanks, I found out it is because how I constructed the filtered agreement array is incorrect. It is resolved now.
